name: Check build latex

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Show Working directory
        run: ls
        
      - name: Setup dsek latex
        uses: actions/checkout@v2
        with:
          repository: Dsek-LTH/dsek-latex
          path: TEX
          
      - name: Show Working directory
        run: ls TEX
        
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
        env:
          TEXINPUTS: ".:./TEX//:"   
